# Generated by Django 2.2.13 on 2020-06-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusSubdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='community',
            old_name='location',
            new_name='point',
        ),
        migrations.AddField(
            model_name='community',
            name='hexuid',
            field=models.IntegerField(default=None, help_text='ID of spatial hex used to color province by connectivity quality.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='census_subdivision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pipeline.CensusSubdivision'),
            preserve_default=False,
        ),
    ]
