# Generated by Django 2.2.13 on 2020-06-30 00:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_auto_20200627_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='censussubdivision',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='community',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
