# Generated by Django 2.2.13 on 2020-06-30 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_auto_20200630_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
                ('sv_reference', models.IntegerField(blank=True, null=True)),
                ('rg_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sv_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('pipeline.location',),
        ),
    ]
