# Generated by Django 2.2 on 2020-07-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_remove_hospital_sv_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='censussubdivision',
            name='name',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
