# Generated by Django 2.2 on 2020-07-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_censussubdivision_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
            ],
            bases=('pipeline.location',),
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=7)),
                ('contact_phone', models.CharField(max_length=30)),
                ('fax_number', models.CharField(max_length=30)),
                ('hours_of_operation', models.CharField(max_length=255)),
                ('court_level', models.CharField(max_length=20)),
            ],
            bases=('pipeline.location',),
        ),
        migrations.CreateModel(
            name='EconomicProject',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
            ],
            bases=('pipeline.location',),
        ),
        migrations.CreateModel(
            name='NaturalResourceProject',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
            ],
            bases=('pipeline.location',),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
            ],
            bases=('pipeline.location',),
        ),
        migrations.CreateModel(
            name='ServiceBCLocation',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
            ],
            bases=('pipeline.location',),
        ),
        migrations.AddField(
            model_name='location',
            name='census_subdivision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pipeline.CensusSubdivision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pipeline.Community'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
