# Generated by Django 2.2 on 2020-07-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_auto_20200704_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='hexuid',
            field=models.CharField(help_text='ID of spatial hex used to color province by connectivity quality.', max_length=15),
        ),
    ]
