# Generated by Django 2.2 on 2020-07-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_auto_20200707_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='census_subdivision',
        ),
    ]
