# Generated by Django 2.2.13 on 2020-07-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_remove_location_census_subdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
