# Generated by Django 2.2.13 on 2020-07-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_community_community_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='place_id',
        ),
    ]
