# Generated by Django 2.2.13 on 2020-07-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0012_remove_community_place_id'),
        ('pipeline', '0011_firstresponders'),
    ]

    operations = [
    ]
