# Generated by Django 2.2.13 on 2020-07-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0013_merge_20200709_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstResponders',
            new_name='FirstResponder',
        ),
    ]
