# Generated by Django 2.2.13 on 2020-07-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0016_timberfacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicFacility',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
            ],
            bases=('pipeline.location',),
        ),
    ]
