# Generated by Django 2.2.13 on 2020-07-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0017_civicfacility'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='band_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='base_access_50mbps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='estimated_population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='estimated_total_dwellings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='fn_community_name',
            field=models.CharField(default='', max_length=127, unique=True),
        ),
        migrations.AddField(
            model_name='community',
            name='municipality_classification',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AddField(
            model_name='community',
            name='municipality_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='nation',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='community',
            name='place_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
