# Generated by Django 2.2.13 on 2020-07-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0020_auto_20200711_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='censussubdivision',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='priv_dwel',
            field=models.IntegerField(null=True),
        ),
    ]
