# Generated by Django 2.2.13 on 2020-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0023_auto_20200711_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='sv_reference',
        ),
        migrations.AddField(
            model_name='hospital',
            name='hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sv_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
