# Generated by Django 2.2.13 on 2020-07-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0025_auto_20200712_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='location_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
