# Generated by Django 2.2.13 on 2020-07-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0027_auto_20200713_1857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'point', 'location_type')},
        ),
    ]
