# Generated by Django 2.2.13 on 2020-07-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0028_auto_20200714_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_fuzzy',
            field=models.BooleanField(default=False, help_text='This field should be set to True if the `point` field was not present in the original dataset and is inferred or approximated by other fields.'),
        ),
    ]
