# Generated by Django 2.2.13 on 2020-07-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0030_auto_20200714_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='num_timber_facilities',
            field=models.IntegerField(null=True),
        ),
    ]
