# Generated by Django 2.2.13 on 2020-07-16 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0031_community_num_timber_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Area')),
                ('oc_m_yr', models.CharField(help_text='The four-digit year that the most recent Order-In-Council or Ministerial Order was approved,  e.g., 2014.', max_length=4)),
            ],
            bases=('pipeline.area',),
        ),
    ]
