# Generated by Django 2.2.13 on 2020-07-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0033_road'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='municipality_id',
        ),
        migrations.AddField(
            model_name='community',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Municipality'),
        ),
    ]
