# Generated by Django 2.2.13 on 2020-07-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0034_auto_20200721_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSecondaryInstitution',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
                ('institution_type', models.CharField(blank=True, max_length=255, null=True)),
                ('economic_development_region', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('pipeline.location',),
        ),
    ]
