# Generated by Django 2.2.13 on 2020-07-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0036_auto_20200721_0023'),
        ('pipeline', '0035_postsecondaryinstitution'),
    ]

    operations = [
    ]
