# Generated by Django 2.2.13 on 2020-07-22 07:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0037_merge_20200722_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hex',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('avail_5_1', models.BooleanField()),
                ('avail_10_2', models.BooleanField()),
                ('avail_25_5', models.BooleanField()),
                ('avail_50_10', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ISP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pipeline.Hex')),
                ('isp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.ISP')),
            ],
        ),
    ]
