# Generated by Django 2.2.13 on 2020-07-22 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0040_auto_20200722_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='hexuid',
            field=models.ForeignKey(db_column='hexuid', help_text='ID of spatial hex used to color province by connectivity quality.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Hex'),
        ),
    ]
