# Generated by Django 2.2.13 on 2020-07-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0042_auto_20200723_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='base_access_50mbps',
        ),
        migrations.RemoveField(
            model_name='community',
            name='estimated_population',
        ),
        migrations.RemoveField(
            model_name='community',
            name='estimated_total_dwellings',
        ),
        migrations.RemoveField(
            model_name='community',
            name='municipality_classification',
        ),
        migrations.AddField(
            model_name='community',
            name='incorporated',
            field=models.NullBooleanField(),
        ),
    ]
