# Generated by Django 2.2.13 on 2020-07-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0043_auto_20200723_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='percent_25_5',
            field=models.FloatField(blank=True, help_text='portion (0-1) of area with 25/5 speeds (calc. by road length)', null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='percent_50_10',
            field=models.FloatField(blank=True, help_text='portion (0-1) of area with 50/10 speeds (calc. by road length)', null=True),
        ),
    ]
