# Generated by Django 2.2.13 on 2020-07-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0044_auto_20200724_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='place_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
