# Generated by Django 2.2.13 on 2020-08-04 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0048_auto_20200804_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_0_4',
            new_name='pop_0_4',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_100',
            new_name='pop_100',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_10_14',
            new_name='pop_10_14',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_15_19',
            new_name='pop_15_19',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_20_24',
            new_name='pop_20_24',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_25_29',
            new_name='pop_25_29',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_30_34',
            new_name='pop_30_34',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_35_39',
            new_name='pop_35_39',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_40_44',
            new_name='pop_40_44',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_45_49',
            new_name='pop_45_49',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_50_54',
            new_name='pop_50_54',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_55_59',
            new_name='pop_55_59',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_5_9',
            new_name='pop_5_9',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_60_64',
            new_name='pop_60_64',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_65_69',
            new_name='pop_65_69',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_70_74',
            new_name='pop_70_74',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_75_79',
            new_name='pop_75_79',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_80_84',
            new_name='pop_80_84',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_85_89',
            new_name='pop_85_89',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_90_94',
            new_name='pop_90_94',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='pop_pct_95_99',
            new_name='pop_95_99',
        ),
    ]
