# Generated by Django 2.2.13 on 2020-08-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0049_auto_20200804_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_0_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_100',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_10_14',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_15_19',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_20_24',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_25_29',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_30_34',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_35_39',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_40_44',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_45_49',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_50_54',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_55_59',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_5_9',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_60_64',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_65_69',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_70_74',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_75_79',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_80_84',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_85_89',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_90_94',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='pop_95_99',
            field=models.IntegerField(null=True),
        ),
    ]
