# Generated by Django 2.2.13 on 2020-08-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0050_auto_20200804_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
