# Generated by Django 2.2.13 on 2020-08-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0054_auto_20200815_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='censussubdivision',
            name='lang_1_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='lang_1_name',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='lang_2_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='lang_2_name',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='lang_3_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='lang_3_name',
            field=models.IntegerField(null=True),
        ),
    ]
