# Generated by Django 2.2.13 on 2020-08-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0056_auto_20200815_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='has_any_k12_school',
            field=models.NullBooleanField(),
        ),
    ]
