# Generated by Django 2.2.13 on 2020-08-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0057_community_has_any_k12_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationdistance',
            name='driving_route_available',
        ),
        migrations.AddField(
            model_name='locationdistance',
            name='driving_distance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Driving distance from community to Location (km)', max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='locationdistance',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Birds' eye distance from community to Location (km)", max_digits=24, null=True),
        ),
    ]
