# Generated by Django 2.2.13 on 2020-08-21 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0058_auto_20200820_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalDistrict',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Area')),
            ],
            bases=('pipeline.area',),
        ),
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Area')),
                ('school_district_number', models.CharField(max_length=5)),
            ],
            bases=('pipeline.area',),
        ),
    ]
