# Generated by Django 2.2.13 on 2020-08-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0060_auto_20200821_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionaldistrict',
            name='oc_m_yr',
            field=models.CharField(help_text='The four-digit year that the most recent Order-In-Council or Ministerial Order was approved,  e.g., 2014.', max_length=4, null=True),
        ),
    ]
