# Generated by Django 2.2.13 on 2020-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0061_regionaldistrict_oc_m_yr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censussubdivision',
            name='eng_fr_not_known',
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='fr_known',
            field=models.IntegerField(null=True),
        ),
    ]
