# Generated by Django 2.2.13 on 2020-08-25 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0061_regionaldistrict_oc_m_yr'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='regional_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.RegionalDistrict'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.SchoolDistrict'),
        ),
        migrations.AddField(
            model_name='schooldistrict',
            name='community',
            field=models.ManyToManyField(to='pipeline.Community'),
        ),
    ]
