# Generated by Django 2.2.13 on 2020-08-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0062_auto_20200825_2231'),
        ('pipeline', '0062_auto_20200826_1735'),
    ]

    operations = [
    ]
