# Generated by Django 2.2.13 on 2020-08-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0063_merge_20200826_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='households_owner_spending_30_pct_income',
            new_name='households_owner_pct_spending_30_pct_income',
        ),
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='households_tenant_spending_30_pct_income',
            new_name='households_tenant_pct_spending_30_pct_income',
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='households_owner_count_mortgage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='households_owner_count_spending_30_pct_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='households_tenant_count_spending_30_pct_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='households_tenant_count_subsidized_housing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='pop_count_0_14',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='pop_count_14_65',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='pop_count_65',
            field=models.IntegerField(null=True),
        ),
    ]
