# Generated by Django 2.2.13 on 2020-08-30 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0070_area_area_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedMill',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
            ],
            bases=('pipeline.location',),
        ),
    ]
