# Generated by Django 2.2.13 on 2020-09-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0071_closedmill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='censussubdivision',
            old_name='married_or_common_law',
            new_name='married_common_law_couples',
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='household_size_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='total_census_families',
            field=models.IntegerField(null=True),
        ),
    ]
