# Generated by Django 2.2.13 on 2020-09-04 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0072_auto_20200903_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='area_ptr',
        ),
        migrations.RemoveField(
            model_name='regionaldistrict',
            name='area_ptr',
        ),
        migrations.RemoveField(
            model_name='schooldistrict',
            name='area_ptr',
        ),
        migrations.RemoveField(
            model_name='schooldistrict',
            name='community',
        ),
        migrations.RemoveField(
            model_name='tsunamizone',
            name='area_ptr',
        ),
        migrations.RemoveField(
            model_name='wildfirezone',
            name='area_ptr',
        ),
        migrations.RemoveField(
            model_name='community',
            name='census_subdivision',
        ),
        migrations.RemoveField(
            model_name='community',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='community',
            name='regional_district',
        ),
        migrations.RemoveField(
            model_name='community',
            name='tsunami_zone',
        ),
        migrations.RemoveField(
            model_name='community',
            name='wildfire_zone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_district',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='RegionalDistrict',
        ),
        migrations.DeleteModel(
            name='SchoolDistrict',
        ),
        migrations.DeleteModel(
            name='TsunamiZone',
        ),
        migrations.DeleteModel(
            name='WildfireZone',
        ),
    ]
