# Generated by Django 2.2.13 on 2020-09-04 03:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0073_auto_20200904_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(help_text='Original ID of data point', null=True)),
                ('name', models.CharField(max_length=127)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('geom_simplified', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('oc_m_yr', models.CharField(help_text='The four-digit year that the most recent Order-In-Council or Ministerial Order was approved,  e.g., 2014.', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(help_text='Original ID of data point', null=True)),
                ('name', models.CharField(max_length=127)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('geom_simplified', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('oc_m_yr', models.CharField(help_text='The four-digit year that the most recent Order-In-Council or Ministerial Order was approved,  e.g., 2014.', max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TsunamiZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(help_text='Original ID of data point', null=True)),
                ('name', models.CharField(max_length=127)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('geom_simplified', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('zone_class', models.CharField(help_text='See https://www2.gov.bc.ca/gov/content/safety/emergency-preparedness-response-recovery/preparedbc/know-your-hazards/tsunamis - A-C:moderate D,E:low', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WildfireZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(help_text='Original ID of data point', null=True)),
                ('name', models.CharField(max_length=127)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('geom_simplified', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('risk_class', models.CharField(help_text='A class value signifying the communities WUI Risk Class rating between 1 (low) and 5 (extreme).', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='census_subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.CensusSubdivision'),
        ),
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(help_text='Original ID of data point', null=True)),
                ('name', models.CharField(max_length=127)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('geom_simplified', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('sd_num', models.CharField(max_length=5)),
                ('community', models.ManyToManyField(to='pipeline.Community')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Municipality'),
        ),
        migrations.AddField(
            model_name='community',
            name='regional_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.RegionalDistrict'),
        ),
        migrations.AddField(
            model_name='community',
            name='tsunami_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.TsunamiZone'),
        ),
        migrations.AddField(
            model_name='community',
            name='wildfire_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.WildfireZone'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.SchoolDistrict'),
        ),
    ]
