# Generated by Django 2.2.13 on 2020-09-04 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0074_auto_20200904_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCentre',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
                ('research_specialties', models.CharField(blank=True, max_length=255, null=True)),
                ('research_centre_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('inst_acrnm', models.CharField(blank=True, max_length=255, null=True)),
                ('research_sector', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('pipeline.location',),
        ),
    ]
