# Generated by Django 2.2.13 on 2020-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0075_researchcentre'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchcentre',
            name='cntr_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchcentre',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
