# Generated by Django 2.2.13 on 2020-09-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0076_auto_20200904_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='parent_community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Community'),
        ),
    ]
