# Generated by Django 2.2.13 on 2020-09-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0077_community_parent_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='parent_community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_communities', to='pipeline.Community'),
        ),
    ]
