# Generated by Django 2.2.13 on 2020-09-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0078_auto_20200904_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='censussubdivision',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='civicfacility',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='closedmill',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ('place_name',), 'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='diagnosticfacility',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='economicproject',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='firstresponder',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='locationdistance',
            options={'ordering': ('id',), 'verbose_name': 'Location Distance', 'verbose_name_plural': 'Location Distances'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='naturalresourceproject',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='postsecondaryinstitution',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='regionaldistrict',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='researchcentre',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='schooldistrict',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='servicebclocation',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='timberfacility',
            options={'ordering': ('id',)},
        ),
    ]
