# Generated by Django 2.2.13 on 2020-09-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0079_auto_20200908_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
                ('descriptn', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('aer_status', models.CharField(blank=True, max_length=255, null=True)),
                ('aircr_acs', models.CharField(blank=True, max_length=255, null=True)),
                ('data_srce', models.CharField(blank=True, max_length=255, null=True)),
                ('datasrc_yr', models.CharField(blank=True, max_length=255, null=True)),
                ('elevation', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_avail', models.CharField(blank=True, max_length=255, null=True)),
                ('heli_acs', models.CharField(blank=True, max_length=255, null=True)),
                ('iata', models.CharField(blank=True, max_length=255, null=True)),
                ('mx_rway_ln', models.CharField(blank=True, max_length=255, null=True)),
                ('num_rway', models.CharField(blank=True, max_length=255, null=True)),
                ('rway_surf', models.CharField(blank=True, max_length=255, null=True)),
                ('oil_avail', models.CharField(blank=True, max_length=255, null=True)),
                ('seapln_acc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('pipeline.location',),
        ),
    ]
