# Generated by Django 2.2.13 on 2020-09-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0080_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='nearest_substation_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='nearest_substation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='nearest_transmission_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='power_pop_2km_capacity',
            field=models.FloatField(blank=True, help_text='POP Capacity (Gbps) for communities that are within 2km of POP', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='power_remaining_pop_capacity',
            field=models.FloatField(blank=True, help_text='Remaining Capacity of POP (Gbps) - (-1 indicates capacity is unknown)', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='transmission_line_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='transmission_line_voltage',
            field=models.FloatField(blank=True, help_text='Transmission Line Voltage (kV)', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='transmission_lines_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
