# Generated by Django 2.2.13 on 2020-09-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0081_auto_20200908_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='community',
            new_name='closest_community',
        ),
    ]
