# Generated by Django 2.2.13 on 2020-09-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0082_auto_20200910_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='num_communities_served',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
