# Generated by Django 2.2.13 on 2020-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0084_auto_20200910_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='censussubdivision',
            name='edu_field_total',
            field=models.IntegerField(null=True),
        ),
    ]
