# Generated by Django 2.2.13 on 2020-09-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0085_censussubdivision_edu_field_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='censussubdivision',
            name='housing_cond_total_private_dwellings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='immigration_population_total',
            field=models.IntegerField(null=True),
        ),
    ]
