# Generated by Django 2.2.13 on 2020-09-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0088_auto_20200917_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censussubdivision',
            name='official_lang_both_eng_fr',
        ),
        migrations.RemoveField(
            model_name='censussubdivision',
            name='official_lang_eng',
        ),
        migrations.RemoveField(
            model_name='censussubdivision',
            name='official_lang_fr',
        ),
        migrations.RemoveField(
            model_name='censussubdivision',
            name='official_lang_neither_eng_fr',
        ),
        migrations.AddField(
            model_name='censussubdivision',
            name='total_lang',
            field=models.IntegerField(null=True),
        ),
    ]
