# Generated by Django 2.2.13 on 2020-09-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0089_auto_20200924_0409'),
        ('pipeline', '0089_dataset'),
    ]

    operations = [
    ]
