# Generated by Django 2.2.13 on 2020-09-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0091_dataset_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='csv_path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='permalink_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='resource_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
