# Generated by Django 2.2.13 on 2020-09-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0095_auto_20200925_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source',
            field=models.CharField(choices=[('internal', 'Provided by Network BC team'), ('databc', 'BC Data Catalogue')], max_length=127, null=True),
        ),
    ]
