# Generated by Django 2.2.13 on 2020-09-29 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0096_auto_20200928_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pipeline.Community')),
            ],
        ),
    ]
