# Generated by Django 2.2.13 on 2020-10-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0097_mayor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mayor',
            options={'ordering': ('id',)},
        ),
    ]
