# Generated by Django 2.2.13 on 2020-10-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0099_auto_20201006_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='permalink_id',
            field=models.CharField(help_text='Permalink ID for datasets from the BC Data Catalogue', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='resource_id',
            field=models.CharField(help_text='Resource ID for datasets from the BC Data Catalogue or Open Government', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='sub_resource_id',
            field=models.CharField(help_text='Sub-resource ID for datasets from Open Government', max_length=255, null=True),
        ),
    ]
