# Generated by Django 2.2.13 on 2020-10-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0100_auto_20201006_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('mayor', 'Mayor'), ('councillor', 'Councillor')], max_length=255)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pipeline.Community')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ('id',)},
        ),
        migrations.DeleteModel(
            name='Mayor',
        ),
    ]
