# Generated by Django 2.2.13 on 2020-10-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0105_auto_20201023_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clean_energy_ind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_jobs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='federal_funding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='green_building_ind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='indigenous_ind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='municipal_funding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='operating_jobs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_public_funding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='provinvial_funding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_funding_ind',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
