# Generated by Django 2.2.13 on 2020-10-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0106_auto_20201023_2249'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
    ]
