# Generated by Django 2.2.13 on 2020-10-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0108_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
