# Generated by Django 2.2.13 on 2020-10-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0109_project_source_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='censussubdivision',
            name='indigenous_population',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_earliest_entry',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='project',
            name='is_latest_entry',
            field=models.NullBooleanField(),
        ),
    ]
