# Generated by Django 2.2.13 on 2020-10-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0110_auto_20201027_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='regionaldistrict',
            options={'ordering': ('name',)},
        ),
    ]
