# Generated by Django 2.2.13 on 2020-10-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0111_auto_20201027_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='url',
            field=models.URLField(),
        ),
    ]
