version: '3.3'

services:
  smtp:
    image: namshi/smtp
    networks:
      - back-tier
  cit-web:
    command: bash -c "yarn && yarn build && yarn start"
    environment:
      - NODE_ENV=production
      - POWERBI_REPORT_ID=ef9fbbd5-63c7-45e8-b9cf-97fc12319be1
      - API_HOST=https://cit-develop.countable.ca
  nginx:
    ports:
      - 10081:80
    volumes:
      - ./nginx/conf.d/default_password_auth.conf:/etc/nginx/conf.d/default.conf
      - .htpasswd:/etc/nginx/.htpasswd
      - static:/static
