sonar.projectKey=bcgov_CIT
sonar.organization=bcgov-sonarcloud

# Include both frontend and backend sources
sonar.sources=cit3.0-web/src,cit-api

# Include frontend test files (not in a separate folder)
sonar.tests=cit3.0-web/src,cit-api/tests
sonar.test.inclusions=cit3.0-web/src/**/*.test.jsx,cit3.0-web/src/**/*.test.tsx

# Frontend (JS/TS) coverage
sonar.javascript.lcov.reportPaths=cit3.0-web/src/coverage/lcov.info

# Backend (Python) coverage
sonar.python.coverage.reportPaths=cit-api/coverage.xml