kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin_devops_engineers
  namespace: {{ .Values.license_plate }}-dev
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: bashbang@github
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: jjstratton@github
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: areyeslo@github
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin_devops_engineers
  namespace: {{ .Values.license_plate }}-test
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: bashbang@github
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: jjstratton@github
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: areyeslo@github
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin_devops_engineers
  namespace: {{ .Values.license_plate }}-prod
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: bashbang@github
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: jjstratton@github
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin_devops_engineers
  namespace: {{ .Values.license_plate }}-tools
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: bashbang@github
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: jjstratton@github
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
