// Notification actions
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_USER_INFO_NAME = "SET_USER_INFO_NAME";
export const SET_USER_INFO_EMAIL = "SET_USER_INFO_EMAIL";
export const SET_USER_INFO_ROLE = "SET_USER_INFO_ROLE";
export const SET_USER_INFO_MUNICIPALITY = "SET_USER_INFO_MUNICIPALITY";
export const SET_USER_INFO_REGIONAL_DISTRICT =
  "SET_USER_INFO_REGIONAL_DISTRICT";
