#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    DROP USER IF EXISTS $POSTGRES_DJANGO_USER;
    CREATE USER $POSTGRES_DJANGO_USER with PASSWORD '$POSTGRES_DJANGO_PASSWORD';
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public to $POSTGRES_DJANGO_USER;
    GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public to $POSTGRES_DJANGO_USER;
    ALTER DEFAULT PRIVILEGES FOR USER $POSTGRES_DJANGO_USER GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $POSTGRES_DJANGO_USER;
    ALTER DEFAULT PRIVILEGES FOR USER $POSTGRES_DJANGO_USER GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO $POSTGRES_DJANGO_USER;
EOSQL
