# Generated by Django 2.2 on 2020-07-04 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_auto_20200704_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='census_subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.CensusSubdivision'),
        ),
    ]
