# Generated by Django 2.2.13 on 2020-08-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0055_auto_20200815_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censussubdivision',
            name='lang_1_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='lang_2_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='lang_3_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
