# Generated by Django 2.2.13 on 2020-09-14 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0086_auto_20200911_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdistance',
            name='within_municipality',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='locationdistance',
            name='community',
            field=models.ForeignKey(help_text='Community for this distance', on_delete=django.db.models.deletion.DO_NOTHING, related_name='distances', to='pipeline.Community'),
        ),
    ]
