# Generated by Django 2.2.13 on 2020-09-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0092_auto_20200925_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='csv_path',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='display_name',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='model_name',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='permalink_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='resource_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal'), ('databc', 'BC Data Catalogue')], max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='source_type',
            field=models.CharField(choices=[('CSV', 'CSV'), ('API', 'DATABC'), ('SHP', 'SHP')], max_length=127, null=True),
        ),
    ]
