# Generated by Django 2.2.13 on 2020-10-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0101_auto_20201006_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civicleader',
            name='position',
            field=models.CharField(choices=[('mayor', 'Mayor'), ('councillor', 'Councillor')], max_length=255),
        ),
    ]
