# Generated by Django 2.2.16 on 2021-01-28 18:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0115_auto_20210126_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investment',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
