# Generated by Django 2.2.16 on 2021-02-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0116_auto_20210128_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investment',
            new_name='Opportunity',
        ),
    ]
