# Generated by Django 2.2.16 on 2021-02-17 19:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0116_auto_20210128_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStatus',
            fields=[
                ('status_name', models.CharField(max_length=255)),
                ('status_description', models.CharField(max_length=255)),
                ('status_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('approval_status', models.ForeignKey(default='PEND', on_delete=django.db.models.deletion.PROTECT, to='pipeline.ApprovalStatus')),
            ],
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
