# Generated by Django 2.2.16 on 2021-02-10 22:46

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0117_auto_20210210_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255)),
                ('status_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='approval_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pipeline.ApprovalStatus'),
        ),
    ]
