# Generated by Django 2.2.16 on 2021-02-12 23:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0118_auto_20210210_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstatus',
            name='id',
        ),
        migrations.AddField(
            model_name='approvalstatus',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='approvalstatus',
            name='status_code',
            field=models.CharField(default='CODE', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='approval_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pipeline.ApprovalStatus'),
        ),
    ]
