# Generated by Django 2.2.16 on 2021-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0119_auto_20210223_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='pid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
