# Generated by Django 2.2.16 on 2021-02-28 19:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0119_auto_20210226_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcfloodplain',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='bcfloodplain',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='censuseconomicregion',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='censuseconomicregion',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='censussubdivision',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='community',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='healthauthorityboundary',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='healthauthorityboundary',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='lake',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='lake',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='naturalresourceregion',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='naturalresourceregion',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=3005),
        ),
        migrations.AlterField(
            model_name='permittedmajormines',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='permittedmajormines',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='provincialelectoraldistrict',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='provincialelectoraldistrict',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='railway',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='railway',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='regionaldistrict',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='regionaldistrict',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='river',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='river',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='road',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='schooldistrict',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='schooldistrict',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='tsunamizone',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='tsunamizone',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='wildfirezone',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
        migrations.AlterField(
            model_name='wildfirezone',
            name='geom_simplified',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
    ]
