# Generated by Django 2.2.16 on 2021-02-13 00:00

from django.db import migrations

def populate_statuses(apps, schema_editor):
    ApprovalStatus = apps.get_model("pipeline", "ApprovalStatus")
    statuses = [
        ["Pending Review", "Opportunity has been submitted and is awaiting approval.", "PEND"],
        ["Needs to be edited", "Opportunity has been sent back for editing.", "EDIT"],
        ["Not completed", "Opportunity has been saved by submitter in an incomplete state.", "NCOM"],
        ["Published", "Opportunity has been approved and is now publicly viewable.", "PUBL"]
    ]
    for status in statuses:
        approval_status = ApprovalStatus()
        approval_status.status_name = status[0]
        approval_status.status_description = status[1]
        approval_status.status_code = status[2]
        approval_status.active_status = True
        approval_status.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0119_auto_20210212_2354'),
    ]

    operations = [
        migrations.RunPython(populate_statuses)
    ]
