# Generated by Django 2.2.16 on 2021-02-13 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0120_auto_20210213_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='approval_status',
            field=models.ForeignKey(default='PEND', on_delete=django.db.models.deletion.PROTECT, to='pipeline.ApprovalStatus'),
        ),
    ]
