# Generated by Django 2.2.16 on 2021-02-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0121_auto_20210213_0008'),
    ]

    operations = [
        # Have to change this field's type manually due to a bug in Django: https://code.djangoproject.com/ticket/25012
        migrations.RunSQL('ALTER TABLE pipeline_opportunity ALTER approval_status_id TYPE varchar(255);'),
    ]
