# Generated by Django 2.2.16 on 2021-03-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0121_auto_20210301_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='river',
            old_name='river_id',
            new_name='area_id',
        ),
    ]
