# Generated by Django 2.2.16 on 2021-03-05 22:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0122_auto_20210301_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='parcel_geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3005),
        ),
    ]
