# Generated by Django 2.2.16 on 2021-03-09 16:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0123_opportunity_parcel_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='parcel_geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=3005),
        ),
    ]
