# Generated by Django 2.2.16 on 2021-03-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0124_auto_20210309_1650'),
        ('pipeline', '0123_auto_20210303_2236'),
    ]

    operations = [
    ]
