# Generated by Django 2.2.16 on 2021-03-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0125_merge_20210309_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
