# Generated by Django 2.2.16 on 2021-03-13 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0126_auto_20210310_1907'),
        ('pipeline', '0126_auto_20210311_2036'),
    ]

    operations = [
    ]
