# Generated by Django 2.2.16 on 2021-03-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0126_auto_20210311_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportDistance',
            fields=[
                ('airport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Airport')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.airport',),
        ),
        migrations.CreateModel(
            name='CommunityDistance',
            fields=[
                ('community_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Community')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.community',),
        ),
        migrations.CreateModel(
            name='CustomsPortOfEntryDistance',
            fields=[
                ('customsportofentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.CustomsPortOfEntry')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.customsportofentry',),
        ),
        migrations.CreateModel(
            name='FirstResponderDistance',
            fields=[
                ('firstresponder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.FirstResponder')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.firstresponder',),
        ),
        migrations.CreateModel(
            name='HospitalDistance',
            fields=[
                ('hospital_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Hospital')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.hospital',),
        ),
        migrations.CreateModel(
            name='IndianReserveBandDistance',
            fields=[
                ('indianreservebandname_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.IndianReserveBandName')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.indianreservebandname',),
        ),
        migrations.CreateModel(
            name='LakeDistance',
            fields=[
                ('lake_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Lake')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.lake',),
        ),
        migrations.CreateModel(
            name='MunicipalityDistance',
            fields=[
                ('municipality_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Municipality')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.municipality',),
        ),
        migrations.CreateModel(
            name='PortAndTerminalDistance',
            fields=[
                ('portandterminal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.PortAndTerminal')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.portandterminal',),
        ),
        migrations.CreateModel(
            name='RailwayDistance',
            fields=[
                ('railway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Railway')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.railway',),
        ),
        migrations.CreateModel(
            name='ResearchCentreDistance',
            fields=[
                ('researchcentre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.ResearchCentre')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.researchcentre',),
        ),
        migrations.CreateModel(
            name='RiverDistance',
            fields=[
                ('river_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.River')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.river',),
        ),
        migrations.CreateModel(
            name='RoadsAndHighwaysDistance',
            fields=[
                ('roadsandhighways_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.RoadsAndHighways')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            bases=('pipeline.roadsandhighways',),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='community_id',
            field=models.ForeignKey(db_column='community_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.CommunityDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_airport',
            field=models.ForeignKey(db_column='nearest_airport', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.AirportDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_ambulance_station',
            field=models.ForeignKey(db_column='nearest_ambulance_station', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_station', to='pipeline.FirstResponderDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_coast_guard_station',
            field=models.ForeignKey(db_column='nearest_coast_guard_station', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coast_guard_station', to='pipeline.FirstResponderDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_customs_port_of_entry',
            field=models.ForeignKey(db_column='nearest_customs_port_of_entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.CustomsPortOfEntryDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_fire_station',
            field=models.ForeignKey(db_column='nearest_fire_station', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_station', to='pipeline.FirstResponderDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_first_nations',
            field=models.ManyToManyField(db_column='nearest_first_nations', null=True, to='pipeline.IndianReserveBandDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_health_center',
            field=models.ForeignKey(db_column='nearest_health_center', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.HospitalDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_highway',
            field=models.ForeignKey(db_column='nearest_highway', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.RoadsAndHighwaysDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_lake',
            field=models.ForeignKey(db_column='nearest_lake', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.LakeDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_municipalities',
            field=models.ManyToManyField(db_column='nearest_municipalities', null=True, to='pipeline.MunicipalityDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_police_station',
            field=models.ForeignKey(db_column='nearest_police_station', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_station', to='pipeline.FirstResponderDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_port',
            field=models.ForeignKey(db_column='nearest_port', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.PortAndTerminalDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_post_secondary',
            field=models.ForeignKey(db_column='nearest_post_secondary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_secondary', to='pipeline.ResearchCentreDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_railway',
            field=models.ForeignKey(db_column='nearest_railway', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.RailwayDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_research_center',
            field=models.ForeignKey(db_column='nearest_research_center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_center', to='pipeline.ResearchCentreDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_river',
            field=models.ForeignKey(db_column='nearest_river', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.RiverDistance'),
        ),
    ]
