# Generated by Django 2.2.16 on 2021-03-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0126_auto_20210311_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='nearest_transmission_line',
            field=models.DecimalField(decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='regional_district_id',
            field=models.ForeignKey(blank=True, db_column='regional_district_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.RegionalDistrict'),
        ),
        migrations.CreateModel(
            name='RoadsAndHighwaysDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highway_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('highway_id', models.ForeignKey(db_column='highway_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.RoadsAndHighways')),
            ],
        ),
        migrations.CreateModel(
            name='RiverDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('river_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('river_id', models.ForeignKey(db_column='river_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.River')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchCentreDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_centre_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('research_centre_id', models.ForeignKey(db_column='research_centre_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.ResearchCentre')),
            ],
        ),
        migrations.CreateModel(
            name='RailwayDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('railway_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('railway_id', models.ForeignKey(db_column='railway_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Railway')),
            ],
        ),
        migrations.CreateModel(
            name='PostSecondaryDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('location_id', models.ForeignKey(db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Location')),
            ],
        ),
        migrations.CreateModel(
            name='PortAndTerminalDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('port_id', models.ForeignKey(db_column='port_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.PortAndTerminal')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('municipality_id', models.ForeignKey(db_column='municipality_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='LakeDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lake_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('lake_id', models.ForeignKey(db_column='lake_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Lake')),
            ],
        ),
        migrations.CreateModel(
            name='IndianReserveBandDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('reserve_id', models.ForeignKey(db_column='reserve_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.IndianReserveBandName')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('hospital_id', models.ForeignKey(db_column='hospital_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='FirstResponderDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_responder_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('first_responder_id', models.ForeignKey(db_column='first_responder_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.FirstResponder')),
            ],
        ),
        migrations.CreateModel(
            name='CustomsPortOfEntryDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customs_port_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('customs_port_id', models.ForeignKey(db_column='port_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.CustomsPortOfEntry')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('community_id', models.ForeignKey(db_column='community_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Community')),
            ],
        ),
        migrations.CreateModel(
            name='AirportDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('airport_id', models.ForeignKey(db_column='airport_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Airport')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='community_id',
            field=models.ForeignKey(blank=True, db_column='community_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.CommunityDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_airport',
            field=models.ForeignKey(blank=True, db_column='nearest_airport', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.AirportDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_ambulance_station',
            field=models.ForeignKey(blank=True, db_column='nearest_ambulance_station', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_station', to='pipeline.FirstResponderDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_coast_guard_station',
            field=models.ForeignKey(blank=True, db_column='nearest_coast_guard_station', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coast_guard_station', to='pipeline.FirstResponderDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_customs_port_of_entry',
            field=models.ForeignKey(blank=True, db_column='nearest_customs_port_of_entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.CustomsPortOfEntryDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_fire_station',
            field=models.ForeignKey(blank=True, db_column='nearest_fire_station', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_station', to='pipeline.FirstResponderDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_first_nations',
            field=models.ManyToManyField(blank=True, db_column='nearest_first_nations', null=True, to='pipeline.IndianReserveBandDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_health_center',
            field=models.ForeignKey(blank=True, db_column='nearest_health_center', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.HospitalDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_highway',
            field=models.ForeignKey(blank=True, db_column='nearest_highway', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.RoadsAndHighwaysDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_lake',
            field=models.ForeignKey(blank=True, db_column='nearest_lake', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.LakeDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_municipalities',
            field=models.ManyToManyField(blank=True, db_column='nearest_municipalities', null=True, to='pipeline.MunicipalityDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_police_station',
            field=models.ForeignKey(blank=True, db_column='nearest_police_station', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_station', to='pipeline.FirstResponderDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_port',
            field=models.ForeignKey(blank=True, db_column='nearest_port', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.PortAndTerminalDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_post_secondary',
            field=models.ForeignKey(blank=True, db_column='nearest_post_secondary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_secondary', to='pipeline.ResearchCentreDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_railway',
            field=models.ForeignKey(blank=True, db_column='nearest_railway', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.RailwayDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_research_center',
            field=models.ForeignKey(blank=True, db_column='nearest_research_center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_center', to='pipeline.ResearchCentreDistance'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='nearest_river',
            field=models.ForeignKey(blank=True, db_column='nearest_river', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.RiverDistance'),
        ),
    ]
