# Generated by Django 2.2.16 on 2021-03-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0127_merge_20210313_0213'),
        ('pipeline', '0127_auto_20210315_2241'),
    ]

    operations = [
    ]
