# Generated by Django 2.2.16 on 2021-03-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0128_merge_20210317_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
