# Generated by Django 2.2.16 on 2021-03-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0128_merge_20210317_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_electrical_connected',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_natual_gas_connected',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_road_connected',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_sewer_connected',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_water_connected',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], default='U', max_length=1),
        ),
    ]
