# Generated by Django 2.2.16 on 2021-03-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0129_auto_20210317_1821'),
        ('pipeline', '0129_auto_20210318_0256'),
    ]

    operations = [
    ]
