# Generated by Django 2.2.16 on 2021-03-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0129_auto_20210317_1821'),
        ('pipeline', '0130_merge_20210318_1840'),
    ]

    operations = [
    ]
