# Generated by Django 2.2.16 on 2021-03-21 22:51

from django.db import migrations, models
import django.db.models.deletion

def add_dummy_user(apps, schema_editor):
    User = apps.get_model("pipeline", "User")
    User.objects.create(name="Unknown", email="Unknown")

def delete_dummy_user(apps, schema_editor):
    User = apps.get_model("pipeline", "User")
    User.objects.get(name="Unknown").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0130_merge_20210319_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(add_dummy_user, delete_dummy_user),
        migrations.RemoveField(
            model_name='opportunity',
            name='regional_district_id',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Municipality'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='regional_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.RegionalDistrict'),
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.Municipality')),
                ('regional_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.RegionalDistrict')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.User')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pipeline.User'),
            preserve_default=False,
        ),
    ]
