# Generated by Django 2.2.16 on 2021-03-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0131_merge_20210319_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='opportunity_natual_gas_capacity',
            new_name='opportunity_natural_gas_capacity',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='opportunity_natual_gas_connected',
            new_name='opportunity_natural_gas_connected',
        ),
    ]
