# Generated by Django 2.2.16 on 2021-03-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0132_auto_20210319_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='nearest_post_secondary',
            field=models.ForeignKey(blank=True, db_column='nearest_post_secondary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_secondary', to='pipeline.PostSecondaryDistance'),
        ),
    ]
