# Generated by Django 2.2.16 on 2021-03-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0132_auto_20210319_2231'),
        ('pipeline', '0134_auto_20210322_1847'),
    ]

    operations = [
    ]
