# Generated by Django 2.2.16 on 2021-03-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0131_auto_20210321_2251'),
        ('pipeline', '0135_merge_20210322_2156'),
    ]

    operations = [
    ]
