# Generated by Django 2.2.16 on 2021-03-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0136_auto_20210323_1547'),
        ('pipeline', '0136_merge_20210323_2026'),
    ]

    operations = [
    ]
