# Generated by Django 2.2.16 on 2021-03-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0139_usertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False, help_text='This is for soft deletes'),
        ),
    ]
