# Generated by Django 2.2.16 on 2021-04-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0139_usertracking'),
        ('pipeline', '0139_auto_20210331_1616'),
    ]

    operations = [
    ]
