# Generated by Django 2.2.16 on 2021-04-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0140_merge_20210401_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='closest_community_distance',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
