# Generated by Django 2.2.16 on 2021-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0140_merge_20210401_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False, help_text='This is for soft deletes'),
        ),
    ]
