# Generated by Django 2.2.16 on 2021-04-06 21:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0142_auto_20210405_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='parcel_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
