# Generated by Django 2.2.16 on 2021-04-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0145_publiclibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstNationsHealthAuthoritySite',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeline.Location')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit_details_1', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit_vendor_1', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit_details_2', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit_vendor_2', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit_details_3', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit_vendor_4', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('pipeline.location',),
        ),
    ]
