# Generated by Django 2.2.16 on 2021-04-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0149_auto_20210416_1946'),
        ('pipeline', '0148_user_is_admin'),
    ]

    operations = [
    ]
