# Generated by Django 2.2.16 on 2021-04-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0149_auto_20210416_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naturalresourceproject',
            name='location_ptr',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='green_building_desc',
            new_name='first_nation_agreement',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='federal_funding',
            new_name='first_nation_ind',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='indigenous_names',
            new_name='first_nation_names',
        ),
        migrations.RemoveField(
            model_name='project',
            name='indigenous_agreement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='indigenous_ind',
        ),
        migrations.RemoveField(
            model_name='project',
            name='municipal_funding',
        ),
        migrations.RemoveField(
            model_name='project',
            name='other_public_funding',
        ),
        migrations.RemoveField(
            model_name='project',
            name='provinvial_funding',
        ),
        migrations.AddField(
            model_name='project',
            name='source_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_fields',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='EconomicProject',
        ),
        migrations.DeleteModel(
            name='NaturalResourceProject',
        ),
    ]
