# Generated by Django 2.2.16 on 2021-04-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0151_auto_20210419_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clean_energy_ind',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='first_nation_ind',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='green_building_ind',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_funding_ind',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
