# Generated by Django 2.2.16 on 2021-04-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0150_merge_20210419_1614'),
        ('pipeline', '0152_auto_20210419_2234'),
    ]

    operations = [
    ]
