# Generated by Django 2.2.16 on 2022-03-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0156_auto_20220215_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census_subdivision_id', models.IntegerField()),
                ('yearmonth', models.CharField(max_length=127, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('total_building_permits', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
            ],
            options={
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='housing_data',
            constraint=models.UniqueConstraint(fields=('census_subdivision_id', 'month', 'year'), name='Primary_Key_Constraint'),
        ),
    ]
