# Generated by Django 2.2.16 on 2022-03-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0157_housing_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing_data',
            name='census_subdivision_name',
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='Month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='housing_data',
            constraint=models.UniqueConstraint(fields=('census_subdivision_id', 'Month', 'year'), name='Primary Key Constraint'),
        ),
    ]
