# Generated by Django 2.2.16 on 2022-02-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0157_nbdphhspeeds_phdemographicdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismRegion',
            fields=[
                ('naics', models.IntegerField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
