# Generated by Django 2.2.16 on 2022-03-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0158_auto_20220308_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbdphhspeeds',
            name='combined_5_1_gov_supp',
            field=models.BooleanField(default=False),
        ),
    ]
