# Generated by Django 2.2.16 on 2022-03-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0159_tourismregion'),
        ('pipeline', '0159_nbdphhspeeds_combined_5_1_gov_supp'),
    ]

    operations = [
    ]
