# Generated by Django 2.2.16 on 2022-03-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0161_linkagewithcensus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkagewithcensus',
            old_name='bc_fire_zone_id',
            new_name='bc_fire_zone',
        ),
        migrations.RenameField(
            model_name='linkagewithcensus',
            old_name='census_subdivision_id',
            new_name='census_subdivision',
        ),
        migrations.RenameField(
            model_name='linkagewithcensus',
            old_name='economic_region_id',
            new_name='economic_region',
        ),
        migrations.RenameField(
            model_name='linkagewithcensus',
            old_name='local_health_area_id',
            new_name='local_health_area',
        ),
        migrations.RenameField(
            model_name='linkagewithcensus',
            old_name='regional_district_id',
            new_name='regional_district',
        ),
        migrations.RenameField(
            model_name='linkagewithcensus',
            old_name='school_district_id',
            new_name='school_district',
        ),
        migrations.RenameField(
            model_name='linkagewithcensus',
            old_name='tourism_region_id',
            new_name='tourism_region',
        ),
        migrations.RenameField(
            model_name='linkagewithcensus',
            old_name='tsunami_notification_zone_id',
            new_name='tsunami_notification_zone',
        ),
    ]
