# Generated by Django 2.2.16 on 2022-03-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0162_merge_20220305_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='cen_prof_detailed_cd_attrs_sp',
            name='pop_total_2021',
            field=models.IntegerField(null=True),
        ),
    ]
