# Generated by Django 2.2.16 on 2022-03-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0162_auto_20220319_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkagewithcensus',
            old_name='local_health_area',
            new_name='health_authority',
        ),
    ]
