# Generated by Django 2.2.16 on 2022-03-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0163_auto_20220320_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='cen_prof_detailed_cd_attrs_sp',
            name='census_division_type_code',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='cen_prof_detailed_cd_attrs_sp',
            name='census_division_type_desc',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cen_prof_detailed_cd_attrs_sp',
            name='pop_2016_2021_pct_change',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cen_prof_detailed_cd_attrs_sp',
            name='pop_total_2021',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cen_prof_detailed_csd_attrs_sp',
            name='census_subdivision_type_code',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='cen_prof_detailed_csd_attrs_sp',
            name='census_subdivision_type_desc',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cen_prof_detailed_csd_attrs_sp',
            name='pop_2016_2021_pct_change',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cen_prof_detailed_csd_attrs_sp',
            name='pop_total_2021',
            field=models.IntegerField(null=True),
        ),
    ]
