# Generated by Django 2.2.16 on 2022-03-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0163_cen_prof_detailed_cd_attrs_sp_pop_total_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='cen_prof_detailed_csd_attrs_sp',
            name='pop_total_2021',
            field=models.IntegerField(null=True),
        ),
    ]
