# Generated by Django 2.2.16 on 2022-04-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0164_auto_20220331_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cen_prof_detailed_cd_attrs_sp',
            old_name='pop_2011_2016_pct_change',
            new_name='pop_2016_2021_pct_change',
        ),
        migrations.RenameField(
            model_name='cen_prof_detailed_csd_attrs_sp',
            old_name='pop_2011_2016_pct_change',
            new_name='pop_2016_2021_pct_change',
        ),
        migrations.RemoveField(
            model_name='cen_prof_detailed_cd_attrs_sp',
            name='pop_total_2011',
        ),
        migrations.RemoveField(
            model_name='cen_prof_detailed_csd_attrs_sp',
            name='pop_total_2011',
        ),
    ]
