# Generated by Django 2.2.16 on 2022-04-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0165_businessesbycsd'),
        ('pipeline', '0165_auto_20220404_2235'),
    ]

    operations = [
    ]
