# Generated by Django 2.2.16 on 2022-04-01 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0165_auto_20220401_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessesByCSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naics_code', models.IntegerField()),
                ('employee_class', models.IntegerField()),
                ('number_of_businesses', models.IntegerField()),
                ('sector', models.CharField(max_length=127, null=True)),
                ('census_subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.CEN_PROF_DETAILED_CSD_ATTRS_SP')),
            ],
        ),
    ]
