# Generated by Django 2.2.16 on 2022-04-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0166_businessesbycsd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessesbycsd',
            name='id',
        ),
        migrations.AlterField(
            model_name='businessesbycsd',
            name='naics_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
