# Generated by Django 2.2.16 on 2022-04-09 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0167_customviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessesbycsd',
            name='census_subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.CEN_PROF_DETAILED_CSD_ATTRS_SP'),
        ),
    ]
