# Generated by Django 2.2.16 on 2022-04-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0167_auto_20220402_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nbdphhspeeds',
            old_name='combined_5_1_gov_supp',
            new_name='combined_50_10_gov_supp',
        ),
    ]
