# Generated by Django 2.2.16 on 2022-04-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0168_auto_20220402_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdemographicdistribution',
            name='census_subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.CEN_PROF_DETAILED_CSD_ATTRS_SP'),
        ),
    ]
