# Generated by Django 2.2.16 on 2022-04-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0168_auto_20220409_0438'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='tsunamizone',
            name='tsunami_zone_name',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='businessesbycsd',
            name='census_subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.CEN_PROF_DETAILED_CSD_ATTRS_SP'),
        ),
    ]
