# Generated by Django 2.2.16 on 2022-04-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0169_auto_20220416_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectivityInfrastructureProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField()),
                ('project_name', models.CharField(max_length=127)),
                ('proponent', models.CharField(max_length=127)),
                ('place_id', models.IntegerField()),
                ('community_name', models.CharField(max_length=127)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('phase', models.CharField(max_length=127)),
                ('num_housesholds_served', models.IntegerField(null=True)),
                ('speed', models.IntegerField()),
                ('type_of_project', models.CharField(max_length=127)),
                ('project_description', models.CharField(max_length=127)),
                ('bc_funding', models.FloatField()),
                ('estimated_start_date', models.DateField(null=True)),
                ('estimated_completion_date', models.DateField(null=True)),
                ('primary_news_release', models.CharField(max_length=127)),
                ('economic_region', models.CharField(max_length=127)),
                ('electoral_name', models.CharField(max_length=127)),
                ('place_type', models.CharField(max_length=127)),
                ('reserve_name', models.CharField(max_length=127, null=True)),
                ('nation', models.CharField(max_length=127, null=True)),
            ],
        ),
    ]
