# Generated by Django 2.2.16 on 2022-04-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0170_auto_20220417_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectivityinfrastructureprojects',
            name='status',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
