# Generated by Django 2.2.16 on 2022-04-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0173_refresh_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildfirezone',
            name='zone_name',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
