# Generated by Django 2.2.16 on 2022-04-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0175_auto_20220424_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAICSCodes',
            fields=[
                ('level', models.IntegerField()),
                ('hierarchical_structure', models.CharField(max_length=255, null=True)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('parent', models.CharField(max_length=255, null=True)),
                ('class_title', models.CharField(max_length=255, null=True)),
            ],
        ),
       
    ]
