# Generated by Django 2.2.16 on 2022-04-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0176_auto_20220425_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkagewithcensus',
            name='natural_resource_region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.NaturalResourceRegion'),
        ),
             migrations.RenameField(
            model_name='linkagewithcensus',
            old_name='natural_resource_region_id',
            new_name='natural_resource_region',
        ),    
    ]
