# Generated by Django 2.2.16 on 2022-05-01 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0177_auto_20220430_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkagewithcensus',
            name='bc_fire_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.WildfireZone'),
        ),
        migrations.AlterField(
            model_name='linkagewithcensus',
            name='census_subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.CEN_PROF_DETAILED_CSD_ATTRS_SP'),
        ),
        migrations.AlterField(
            model_name='linkagewithcensus',
            name='economic_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.CensusEconomicRegion'),
        ),
        migrations.AlterField(
            model_name='linkagewithcensus',
            name='health_authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.HealthAuthorityBoundary'),
        ),
        migrations.AlterField(
            model_name='linkagewithcensus',
            name='natural_resource_region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.NaturalResourceRegion'),
        ),
        migrations.AlterField(
            model_name='linkagewithcensus',
            name='regional_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.RegionalDistrict'),
        ),
        migrations.AlterField(
            model_name='linkagewithcensus',
            name='school_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.SchoolDistrict'),
        ),
        migrations.AlterField(
            model_name='linkagewithcensus',
            name='tourism_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.TourismRegion'),
        ),
        migrations.AlterField(
            model_name='linkagewithcensus',
            name='tsunami_notification_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.TsunamiZone'),
        ),
    ]
