# Generated by Django 2.2.16 on 2022-05-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0179_auto_20220507_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstNationsHealthAuthoritySite',
        ),
    ]
