# Generated by Django 2.2.16 on 2022-05-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0180_auto_20220514_2017'),
        ('pipeline', '0180_change_view'),
    ]

    operations = [
    ]
