# Generated by Django 2.2.28 on 2023-05-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0185_auto_20230510_0445'),
    ]

    operations = [
        migrations.RunSQL("""
            update pipeline_municipalitydistance
            set community_id = community_municipality.community_id
            from (select pipeline_community.id as "community_id", pipeline_community.municipality_id 
                  from pipeline_community
                  left join pipeline_municipalitydistance  
                  on   pipeline_community.municipality_id = pipeline_municipalitydistance.municipality_id 
                 ) community_municipality
            where pipeline_municipalitydistance.community_id is null and 
                pipeline_municipalitydistance.municipality_id = community_municipality.municipality_id;
        """)
    ]
