# Generated by Django 2.2.28 on 2023-05-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0186_populate_community_id_municipalitydistance'),
    ]

    operations = [
        migrations.RunSQL("""
            update pipeline_indianreservebanddistance 
            set community_id = reserve_id
            where community_id is null and 
                  reserve_id in (
                     select pipeline_community.id 
                     from pipeline_community);
        """)
    ]
