# Generated by Django 4.1.7 on 2024-01-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0188_update_approval_status_NCOM'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSDCoreHousingNeed',
            fields=[
                ('census_subdivision_id', models.IntegerField(primary_key=True, serialize=False)),
                ('core_housing_examined', models.IntegerField(null=True)),
                ('core_housing_need', models.IntegerField(null=True)),
                ('core_housing_need_percentage', models.FloatField(null=True)),
            ],
            options={
                'ordering': ('census_subdivision_id',),
            },
        ),
        migrations.AlterField(
            model_name='community',
            name='has_any_k12_school',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='incorporated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_coastal',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='nbdphhspeeds',
            name='phh_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='nearest_first_nations',
            field=models.ManyToManyField(blank=True, db_column='nearest_first_nations', to='pipeline.indianreservebanddistance'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='nearest_municipalities',
            field=models.ManyToManyField(blank=True, db_column='nearest_municipalities', to='pipeline.municipalitydistance'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_preferred_development',
            field=models.ManyToManyField(db_column='opportunity_preferred_development', to='pipeline.preferreddevelopment'),
        ),
        migrations.AlterField(
            model_name='phdemographicdistribution',
            name='phh_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_earliest_entry',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_latest_entry',
            field=models.BooleanField(null=True),
        ),
    ]
