# Generated by Django 4.1.7 on 2024-01-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0188_update_approval_status_NCOM'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSDCoreHousingNeed',
            fields=[
                ('census_subdivision_id', models.IntegerField(primary_key=True, serialize=False)),
                ('core_housing_examined', models.IntegerField(null=True)),
                ('core_housing_need', models.IntegerField(null=True)),
                ('core_housing_need_percentage', models.FloatField(null=True)),
            ],
            options={
                'ordering': ('census_subdivision_id',),
            },
        )
    ]
