# Generated by Django 4.1.7 on 2024-01-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0189_csdcorehousingneed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSDCentroid',
            fields=[
                ('object_id', models.IntegerField(primary_key=True)),
                ('census_year', models.IntegerField(null=True)),
                ('census_subdivision_id', models.IntegerField(null=False, blank=False)),
                ('census_s_1', models.CharField(max_length=127)),
                ('census_s_2', models.CharField(max_length=127)),
                ('census_s_3', models.CharField(max_length=127)),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
            ],
            options={
                'ordering': ('census_subdivision_id',),
            },
        )
    ]
