# Generated by Django 4.1.7 on 2024-02-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0191_municipaltaxrates_alter_csdcentroid_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="csdcentroid",
            table="c2021_FeatureToPoint_TableToExcel",
        ),
    ]
