# Generated by Django 4.1.7 on 2024-02-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0192_rename_csd_centroid_to_match_old_xl_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSDSmallBusinesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census_subdivision_id', models.IntegerField()),
                ('csd_name', models.CharField(max_length=127)),
                ('cd_name', models.CharField(max_length=127)),
                ('dr_name', models.CharField(max_length=127)),
                ('employ_0', models.IntegerField()),
                ('employ_1_4', models.IntegerField()),
                ('employ_5_9', models.IntegerField()),
                ('employ_10_19', models.IntegerField()),
                ('employ_20_49', models.IntegerField()),
                ('employ_50_99', models.IntegerField()),
                ('employ_100_199', models.IntegerField()),
                ('employ_200_499', models.IntegerField()),
                ('employ_1000_1499', models.IntegerField()),
                ('employ_1500_2499', models.IntegerField()),
                ('employ_2500_4999', models.IntegerField()),
                ('employ_5000_more', models.IntegerField()),
                ('subtotal_with_employ_gt_0', models.IntegerField()),
                ('grand_total', models.IntegerField()),
            ],
        )
    ]
