# Generated by Django 4.1.7 on 2024-02-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0193_delete_bad_csd_centroid_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSDCentroid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('census_subdivision_id', models.IntegerField()),
                ('name', models.IntegerField()),
                ('closest_community_id', models.CharField(max_length=127, null=True)),
                ('closest_community_distance', models.CharField(max_length=127, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('Location Name', models.CharField(max_length=127)),
                ('First Responders', models.IntegerField(null=True)),
                ('Diagnostic Facilities', models.IntegerField(null=True)),
                ('Timber Facilities', models.IntegerField(null=True)),
                ('Civic Facilities', models.IntegerField(null=True)),
                ('Airports', models.IntegerField(null=True)),
                ('Port And Terminal', models.IntegerField(null=True)),
                ('Customs Ports Of Entry', models.IntegerField(null=True)),
                ('Local Govt Offices', models.IntegerField(null=True)),
                ('Laboratory Service', models.IntegerField(null=True)),
                ('Emergency Social Service Facilities', models.IntegerField(null=True)),
                ('Pharmacies', models.IntegerField(null=True)),
                ('Economic Projects', models.IntegerField(null=True)),
                ('Hospitals', models.IntegerField(null=True)),
                ('Service BC Locations', models.IntegerField(null=True)),
                ('Schools', models.IntegerField(null=True)),
                ('Clinics', models.IntegerField(null=True)),
                ('Courts', models.IntegerField(null=True)),
                ('Post Secondary Institutions', models.IntegerField(null=True)),
                ('Research Centres', models.IntegerField(null=True)),
                ('Public Library', models.IntegerField(null=True)),
                ('Is within 50 km', models.IntegerField(null=True)),
                ('location_type_id', models.IntegerField(null=True)),
                ('location_website', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'c2021_FeatureToPoint_TableToExcel',
            },
        ),
    ]
