# Generated by Django 4.1.7 on 2024-02-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0193_csdsmallbusinesses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSDCentroid',
        )
    ]
