# Generated by Django 4.1.7 on 2024-02-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0193_delete_bad_csd_centroid_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSDCentroid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('census_subdivision_id', models.IntegerField()),
                ('name', models.CharField(max_length=127, null=True)),
                ('closest_community_id', models.CharField(max_length=127, null=True)),
                ('closest_community_distance', models.CharField(max_length=127, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(max_length=127)),
                ('first_responders', models.IntegerField(null=True)),
                ('diagnostic_facilities', models.IntegerField(null=True)),
                ('timber_facilities', models.IntegerField(null=True)),
                ('civic_facilities', models.IntegerField(null=True)),
                ('airports', models.IntegerField(null=True)),
                ('port_and_terminal', models.IntegerField(null=True)),
                ('customs_ports_of_entry', models.IntegerField(null=True)),
                ('local_govt_offices', models.IntegerField(null=True)),
                ('laboratory_services', models.IntegerField(null=True)),
                ('emergency_social_service_facilities', models.IntegerField(null=True)),
                ('pharmacies', models.IntegerField(null=True)),
                ('economic_projects', models.IntegerField(null=True)),
                ('hospitals', models.IntegerField(null=True)),
                ('service_bc_locations', models.IntegerField(null=True)),
                ('schools', models.IntegerField(null=True)),
                ('clinics', models.IntegerField(null=True)),
                ('courts', models.IntegerField(null=True)),
                ('post_secondary_institutions', models.IntegerField(null=True)),
                ('research_centres', models.IntegerField(null=True)),
                ('public_library', models.IntegerField(null=True)),
                ('is_within_50km', models.IntegerField(null=True)),
                ('location_type_id', models.IntegerField(null=True)),
                ('location_website', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'c2021_FeatureToPoint_TableToExcel',
            },
        ),
    ]
