from django.contrib.gis.db import models
class BCNetworkConnectivity(models.Model):
    bcnc_ncs_sysid = models.FloatField(null=True)
    hex_code_id = models.CharField(max_length=127, primary_key=True)
    population = models.FloatField(null=True)
    total_dwellings = models.FloatField(null=True)
    usual_residences = models.FloatField(null=True)
    td_underserved_50mpbs = models.FloatField(null=True)
    internet_zone = models.FloatField(null=True)
    mobile_wireless_coverage = models.FloatField(null=True)
    percent_served_5_mbps = models.FloatField(null=True)
    percent_served_50_mbps = models.FloatField(null=True)
    cable_providers = models.CharField(max_length=127, null=True)
    fibre_providers = models.CharField(max_length=127, null=True)
    dsl_providers = models.CharField(max_length=127, null=True)
    fixed_wireless_providers = models.CharField(max_length=127, null=True)
    satellite_providers = models.CharField(max_length=127, null=True)
    mobile_wireless_providers = models.CharField(max_length=127, null=True)
    transport_fibre_providers = models.CharField(max_length=127, null=True)