FROM python:3.12 AS compile
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y --no-install-recommends \
    libproj-dev \
    libgdal-dev \
    gdal-bin \
    libgeos-dev \
    libpq-dev \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . .

RUN mv data/import/datafiles/* /code/data
RUN python manage.py collectstatic --noinput

CMD /bin/sh ./entrypoint.pipeline.sh
