FROM python:3.6
ENV PYTHONUNBUFFERED 1


ARG RUNTIME_ENV

RUN apt-get update && apt-get install -y libproj-dev gdal-bin libpq-dev libpython3-dev build-essential

RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . .
RUN rm data/import/datafiles/*
RUN python3 manage.py collectstatic --noinput

CMD /bin/sh ./entrypoint.email.sh