FROM python:3.9
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y libproj-dev gdal-bin libpq-dev libpython3-dev build-essential

RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
#would be better to exclude these instead of copying then deleting them but time ¯\_(ツ)_/¯
COPY . .
RUN rm data/import/datafiles/*
RUN python3 manage.py collectstatic --noinput

CMD ./entrypoint.sh