version: "3.3"

services:
  cit-api-pipeline:
    build:
      context: ./
      dockerfile: docker/Dockerfile.pipeline
    image: countable/cit
    env_file:
      - ../.env
    ports:
      - 8000:8000
