FROM python:3.11-slim-buster as compile
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y --no-install-recommends libproj-dev gdal-bin libpq-dev libpython3-dev build-essential gcc

RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . .

RUN mv data/import/datafiles/* /code/data
RUN python manage.py collectstatic --noinput

CMD /bin/sh ./entrypoint.pipeline.sh
