FROM python:3.6
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y libproj-dev gdal-bin libpq-dev libpython3-dev build-essential

RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . .
COPY ./datafiles/* /code/data
RUN python3 manage.py collectstatic --noinput

CMD /bin/sh ./entrypoint.pipeline.sh