# This workflow will build a new container semiannually running the datasets in Bucket 4 semiannually
# The datasets included in this bucket are, census economic region, courts, 
# health authority boundaries, indian reserve and band name, lakes, natural resource regions,
# post secondary institutions, provincial electoral district, railways, research centres, rivers, 
# road and highways, services


name: Data Pipeline - Bucket 4 semiannually
on:
  schedule:
    - cron: "0 0 1 */6 *"
  workflow_dispatch:
env: 
  BUCKET_COMMAND: bucket_4_semiannually
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
        
      - name: "Generate env file"
        run: |
            echo 'POSTGRES_DB = ${{ secrets.POSTGRES_DB_TEST }}' >> .env 
            echo 'POSTGRES_DJANGO_USER = ${{ secrets.POSTGRES_DJANGO_USER_TEST }}' >> .env 
            echo 'POSTGRES_DJANGO_PASSWORD = ${{ secrets.POSTGRES_DJANGO_PASSWORD_TEST }}' >> .env 
            echo 'POSTGRES_HOST = ${{ secrets.POSTGRES_HOST_TEST }}' >> .env
            echo 'ROUTE_PLANNER_API_KEY = ${{ secrets.ROUTE_PLANNER_API_KEY }}' >> .env 
            echo 'BUCKET_COMMAND = ${{ env.BUCKET_COMMAND }}' >> .env

      - name: Start containers
        run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
      
      # docker-compose will return 0 even if python container returns non-zero or crashes
      # ensure job fails if python container returns non-zero code or crashes
      - name: check Container Status
        run: | 
          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
          if [[ $container_status == *"Exited (0)"* ]]; 
          then 
            echo "Container exited successfully"
          else 
            echo "Container exited with error: $container_status"
            exit 1
          fi
        
  run-prod:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: "Generate env file"
        run: |
            echo 'POSTGRES_DB = ${{ secrets.POSTGRES_DB_PROD }}' >> .env 
            echo 'POSTGRES_DJANGO_USER = ${{ secrets.POSTGRES_DJANGO_USER_PROD }}' >> .env 
            echo 'POSTGRES_DJANGO_PASSWORD = ${{ secrets.POSTGRES_DJANGO_PASSWORD_PROD }}' >> .env 
            echo 'POSTGRES_HOST = ${{ secrets.POSTGRES_HOST_PROD }}' >> .env
            echo 'ROUTE_PLANNER_API_KEY = ${{ secrets.ROUTE_PLANNER_API_KEY }}' >> .env 
            echo 'BUCKET_COMMAND = ${{ env.BUCKET_COMMAND }}' >> .env

      - name: Start containers
        run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline
                
      # docker-compose will return 0 even if python container returns non-zero or crashes
      # ensure job fails if python container returns non-zero code or crashes
      - name: check Container Status
        run: | 
          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
          if [[ $container_status == *"Exited (0)"* ]]; 
          then 
            echo "Container exited successfully"
          else 
            echo "Container exited with error: $container_status"
            exit 1
          fi
        