# This workflow will build a new container weekly running the data pipeline weekly pulls

name: Do things every 5 minutes
on:
  #schedule:
    #- cron: "0 13 * * 1"
    #- cron: "*/1 * * * *"
  push:
    branches:
      - github-actions-data-pipeline
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Test
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az account show
      #- name: "Run Azure container start"
      #  run: |
      #    az container start list --name cit-data-pipeline --resource-group CLNPD1-ZCACN-RGP-CITZ-ICT-Cit01 [--no-wait] [--subscription] BCGov-MGD-CLNPD1
