# This workflow will build a new container weekly running the data pipeline weekly pulls

name: AZ Login
on:
  #schedule:
    #- cron: "0 13 * * 1"
    #- cron: "*/1 * * * *"
  push:
    branches:
      - github-actions-data-pipeline
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Test
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
      
      - name: "Generate env file"
        run: |
            echo 'POSTGRES_DB = ${{ secrets.POSTGRES_DB_TEST }}' >> .env 
            echo 'POSTGRES_DJANGO_USER = ${{ secrets.POSTGRES_DJANGO_USER_TEST }}' >> .env 
            echo 'POSTGRES_DJANGO_PASSWORD = ${{ secrets.POSTGRES_DJANGO_PASSWORD_TEST }}' >> .env 
            echo 'POSTGRES_HOST = ${{ secrets.POSTGRES_HOST_TEST }}' >> .env 

      - name: Start containers
        run: |
            pwd
            docker-compose '/cit-api/docker-compose.yml' up --build
      

      #- name: Log in with Azure
      #  uses: azure/login@v1
      #  with:
      #    creds: ${{ secrets.AZURE_CREDENTIALS }}
      #
      #- name: POSTGRES_CONNECTION
      #  uses: azure/postgresql@v1
      #  with:
      #    server-name: ${{ secrets.AZURE_POSTGRES_TEST_HOST }}
      #    connection-string: psql host=${{ secrets.AZURE_POSTGRES_TEST_HOST }} port=5432 dbname=cit user=${{ secrets.AZURE_POSTGRES_TEST_USERNAME }} password=${{ secrets.AZURE_POSTGRES_TEST_PASSWORD }}
      #    #sql-file: './data.sql'