# This workflow will build a new container running the census dataset
# The datasets included in this bucket are, census, census subdivisions 2016 and census subdivisions

name: Data Pipeline Bucket 1 - Census Datasets Prod
on:
  workflow_dispatch:
jobs:
  run-census-divisions:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
        
      - name: "Generate env file"
        run: |
            echo 'POSTGRES_DB = ${{ secrets.POSTGRES_DB_PROD }}' >> .env 
            echo 'POSTGRES_DJANGO_USER = ${{ secrets.POSTGRES_DJANGO_USER_PROD }}' >> .env 
            echo 'POSTGRES_DJANGO_PASSWORD = ${{ secrets.POSTGRES_DJANGO_PASSWORD_PROD }}' >> .env 
            echo 'POSTGRES_HOST = ${{ secrets.POSTGRES_HOST_PROD }}' >> .env
            echo 'ROUTE_PLANNER_API_KEY = ${{ secrets.ROUTE_PLANNER_API_KEY }}' >> .env 
            echo 'BUCKET_COMMAND = bucket_1_census_divisions' >> .env

      - name: Start containers
        run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline

        # docker-compose will return 0 even if python container returns non-zero or crashes
        # ensure job fails if python container returns non-zero code or crashes
      - name: check Container Status
        run: | 
          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
          if [[ $container_status == *"Exited (0)"* ]]; 
          then 
            echo "Container exited successfully"
          else 
            echo "Container exited with error: $container_status"
            exit 1
          fi
        

  run-census-subdivisions-2016:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
        
      - name: "Generate env file"
        run: |
            echo 'POSTGRES_DB = ${{ secrets.POSTGRES_DB_PROD }}' >> .env 
            echo 'POSTGRES_DJANGO_USER = ${{ secrets.POSTGRES_DJANGO_USER_PROD }}' >> .env 
            echo 'POSTGRES_DJANGO_PASSWORD = ${{ secrets.POSTGRES_DJANGO_PASSWORD_PROD }}' >> .env 
            echo 'POSTGRES_HOST = ${{ secrets.POSTGRES_HOST_PROD }}' >> .env
            echo 'ROUTE_PLANNER_API_KEY = ${{ secrets.ROUTE_PLANNER_API_KEY }}' >> .env 
            echo 'BUCKET_COMMAND = bucket_1_census_subdivisions_2016' >> .env

      - name: Start containers
        run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline

        # docker-compose will return 0 even if python container returns non-zero or crashes
        # ensure job fails if python container returns non-zero code or crashes
      - name: check Container Status
        run: | 
          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
          if [[ $container_status == *"Exited (0)"* ]]; 
          then 
            echo "Container exited successfully"
          else 
            echo "Container exited with error: $container_status"
            exit 1
          fi

  run-census-subdivisions:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
        
      - name: "Generate env file"
        run: |
            echo 'POSTGRES_DB = ${{ secrets.POSTGRES_DB_PROD }}' >> .env 
            echo 'POSTGRES_DJANGO_USER = ${{ secrets.POSTGRES_DJANGO_USER_PROD }}' >> .env 
            echo 'POSTGRES_DJANGO_PASSWORD = ${{ secrets.POSTGRES_DJANGO_PASSWORD_PROD }}' >> .env 
            echo 'POSTGRES_HOST = ${{ secrets.POSTGRES_HOST_PROD }}' >> .env
            echo 'ROUTE_PLANNER_API_KEY = ${{ secrets.ROUTE_PLANNER_API_KEY }}' >> .env 
            echo 'BUCKET_COMMAND = bucket_1_census_subdivisions' >> .env

      - name: Start containers
        run: docker-compose -f cit-api/docker-compose.yml up --build cit-api-pipeline

        # docker-compose will return 0 even if python container returns non-zero or crashes
        # ensure job fails if python container returns non-zero code or crashes
      - name: check Container Status
        run: | 
          container_status=$(docker ps --filter 'status=exited' --format '{{.Status}}')
          if [[ $container_status == *"Exited (0)"* ]]; 
          then 
            echo "Container exited successfully"
          else 
            echo "Container exited with error: $container_status"
            exit 1
          fi        