# This workflow contains all static image scanning
name: scan-images

on:
  workflow_call:

concurrency:
  group: scan-images-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trivy-scan-frontend:
    runs-on: ubuntu-latest
    outputs:
      results-length: ${{ steps.scan-results-length.outputs.results-length }}
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/bcgov/cit/cit-frontend:sha-${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL
          timeout: 10m0s
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@429e1977040da7a23b6822b13c129cd1ba93dbb2
        with:
          sarif_file: "trivy-results.sarif"
      - name: Get Results Length From Sarif
        id: scan-results-length
        run: echo "results-length=$(cat trivy-results.sarif | jq '.runs[0].results | length')" >> $GITHUB_OUTPUT

  trivy-scan-api:
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      results-length: ${{ steps.scan-results-length.outputs.results-length }}
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/bcgov/cit/cit-api:sha-${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL
          timeout: 10m0s
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@429e1977040da7a23b6822b13c129cd1ba93dbb2
        with:
          sarif_file: "trivy-results.sarif"
      - name: Get Results Length From Sarif
        id: scan-results-length
        run: echo "results-length=$(cat trivy-results.sarif | jq '.runs[0].results | length')" >> $GITHUB_OUTPUT
